name: lbh
favicon: null
layout_spectrum: 0.70274
typography_spectrum: 0.4523766818456352
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.0625
  lightness: 0.1808252315968275
  saturation: 0.09353078063577414
  rhythmicContrast: 0.4041985687799752
purpose: []
