name: lbh
favicon: null
layout_spectrum: 0.70274
typography_spectrum: 0.23323
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#353535'
    - '#9a9a9a'
    - '#d8d8d8'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
